[2025-09-03T22:11:20.835+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: continuous_streaming_consumer.continuous_producer_consumer scheduled__2025-09-03T22:09:00+00:00 [queued]>
[2025-09-03T22:11:20.840+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: continuous_streaming_consumer.continuous_producer_consumer scheduled__2025-09-03T22:09:00+00:00 [queued]>
[2025-09-03T22:11:20.841+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-09-03T22:11:20.841+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1000
[2025-09-03T22:11:20.841+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-09-03T22:11:20.848+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): continuous_producer_consumer> on 2025-09-03 22:09:00+00:00
[2025-09-03T22:11:20.850+0000] {standard_task_runner.py:55} INFO - Started process 915 to run task
[2025-09-03T22:11:20.852+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'continuous_streaming_consumer', 'continuous_producer_consumer', 'scheduled__2025-09-03T22:09:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_continuous_consumer.py', '--cfg-path', '/tmp/tmpkzzjwhpt']
[2025-09-03T22:11:20.853+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask continuous_producer_consumer
[2025-09-03T22:11:20.863+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T22:11:20.876+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T22:11:20.896+0000] {task_command.py:388} INFO - Running <TaskInstance: continuous_streaming_consumer.continuous_producer_consumer scheduled__2025-09-03T22:09:00+00:00 [running]> on host 16d99b450999
[2025-09-03T22:11:20.938+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Klaus_Rezende
AIRFLOW_CTX_DAG_ID=continuous_streaming_consumer
AIRFLOW_CTX_TASK_ID=continuous_producer_consumer
AIRFLOW_CTX_EXECUTION_DATE=2025-09-03T22:09:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-09-03T22:09:00+00:00
[2025-09-03T22:11:20.942+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:20.943+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-09-03T22:11:20.943+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Connection complete.
[2025-09-03T22:11:20.948+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:20.948+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-09-03T22:11:20.949+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Connection complete.
[2025-09-03T22:11:21.045+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2025-09-03T22:11:21.045+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-09-03T22:11:21.049+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2025-09-03T22:11:21.050+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-09-03T22:11:21.050+0000] {consumer.py:118} WARNING - group_id is None: disabling auto-commit.
[2025-09-03T22:11:21.050+0000] {subscription_state.py:171} INFO - Updating subscribed topics to: ('streaming_data',)
[2025-09-03T22:11:21.051+0000] {subscription_state.py:257} INFO - Updated partition assignment: [('streaming_data', 0), ('streaming_data', 1), ('streaming_data', 2)]
[2025-09-03T22:11:21.052+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:21.052+0000] {conn.py:410} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Connection complete.
[2025-09-03T22:11:21.052+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. 
[2025-09-03T22:11:21.146+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:21.146+0000] {conn.py:410} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Connection complete.
[2025-09-03T22:11:21.146+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. 
[2025-09-03T22:11:21.148+0000] {logging_mixin.py:137} INFO - Produced post 1: sunt aut facere repellat provi...
[2025-09-03T22:11:22.845+0000] {logging_mixin.py:137} INFO - Consumed from partition 2, key 2: eveniet quod temporibus...
[2025-09-03T22:11:25.391+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connected> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
[2025-09-03T22:11:25.392+0000] {conn.py:1096} ERROR - <BrokerConnection node_id=1 host=kafka:29092 <connected> [IPv4 ('172.16.240.7', 29092)]>: socket disconnected
[2025-09-03T22:11:25.392+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:25.392+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connected> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2025-09-03T22:11:25.392+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:25.393+0000] {future.py:79} ERROR - Fetch to node 1 failed: KafkaConnectionError: socket disconnected
[2025-09-03T22:11:25.393+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:25.393+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:25.394+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:25.394+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:25.443+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:25.444+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:25.444+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:25.444+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:25.545+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:25.546+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:25.546+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:25.546+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:25.646+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:25.646+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:25.646+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:25.646+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:25.797+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:25.798+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:25.798+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:25.798+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:25.898+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:25.899+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:25.899+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:25.899+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:26.202+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:26.202+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:26.203+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:26.203+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:26.403+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:26.404+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:26.404+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:26.404+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
